Document: pileofblocks
Title: Debian pileofblocks Manual
Author: <insert document author here>
Abstract: This manual describes what pileofblocks is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pileofblocks/pileofblocks.sgml.gz

Format: postscript
Files: /usr/share/doc/pileofblocks/pileofblocks.ps.gz

Format: text
Files: /usr/share/doc/pileofblocks/pileofblocks.text.gz

Format: HTML
Index: /usr/share/doc/pileofblocks/html/index.html
Files: /usr/share/doc/pileofblocks/html/*.html
